### ISSUE TITLE
Final location uses backslash in windows os

### ISSUE THREAD

**Issue by xie-sheng** [dbt-athena/dbt-athena#101]
Hi,

After the model generated by DBT Athena,the table location was looks like this

**s3://my-test-bucket/dbt/resident_communication\ticket_last_comment\6975c131-96c7-4b48-baf3-3b18acb6a431** 

and i think it should be like this

**s3://my-test-bucket/dbt/resident_communication/ticket_last_comment/6975c131-96c7-4b48-baf3-3b18acb6a431**

 I think this is cuased by Windows OS path behavior, below is my profile.
  **s3_staging_dir: s3://my-test-bucket/dbt/
  s3_data_dir: s3://my-test-bucket/dbt/
  s3_data_naming: schema_table_unique**

Is there a wrong setting with me?  thank you very much.

**Comment by xie-sheng** [comment]
win10 OS

**Comment by nicor88** [comment]
this behavior is expected, the `s3_data_naming` is set to `schema_table_unique`, that lead to `schema_name/table_name/unique_id/` you can consider to use another s3_data_naming, for example `table` or `schema_table`, but bare in mind that only unique table locations are supported for table_type=Iceberg.

**Comment by xie-sheng** [comment]
Thanks for your reply.

the s3_data_naming is OK for me.

but i was wondered the forward slash and back slash within the path,when i use windows OS, the generated location path is wired as below.
**s3://my-test-bucket/dbt/resident_communication\ticket_last_comment\6975c131-96c7-4b48-baf3-3b18acb6a431**

**Comment by nicor88** [comment]
ah I missed the backslash, the issue is here: https://github.com/dbt-athena/dbt-athena/blob/main/dbt/adapters/athena/impl.py#L81-L87
I think that windows don't return a good `final path due to `os.path.join`

**Comment by mattiamatrix** [comment]
> ah I missed the backslash, the issue is here: https://github.com/dbt-athena/dbt-athena/blob/main/dbt/adapters/athena/impl.py#L81-L87 I think that windows don't return a good final path due to `os.path.join`
> 
> We could consider to add `replace('\', '/)` at the end to fix this. I want to keep the path.join to avoid dealing with final trailing slash in paths.

Looking at the [docs](https://docs.python.org/3.8/library/os.path.html#module-os.path), importing `posixpath` could be a clean solution in this case.

**Comment by nicor88** [comment]
@mattiamatrix thanks, I was not aware of it.
Doing some testing I was to achieve what the current setup does:
`posixpath.join('s3://my_bucket','b')` -> `s3://my_bucket/b`
`posixpath.join('s3://my_bucket/','b')` -> `s3://my_bucket/b`

Should be indeed an easy and more elegant fix.
