### ISSUE TITLE
dbt found two macros named "set_table_classification" in the project   "dbt_athena".

### ISSUE THREAD

**Issue by mrshu** [dbt-athena/dbt-athena#103]
I ran into this when installing `dbt-athena-community` via `pip install dbt-athena-community` on `dbt=1.3.1`.

The issue was that the package `dbt-athena` (https://github.com/Tomme/dbt-athena) has already been installed on the target system, leading to the two macros of the same name being being defined.

The fix was to uninstall one of the `dbt-athena*` packages -- in my case `pip uninstall dbt-athena`.

**Comment by mrshu** [comment]
I only opened this bug for the benefit of anyone who might run into this in the future. I don't think there is much the `dbt-athena` project can do to help with this issue, other than to make sure it can be looked up, which this issue should help with.

I am hence closing it.

**Comment by nicor88** [comment]
@mrshu Thanks for this, actually might make sense to add this to the Readme? A small section that says that if dbt-athena-adapter is already installed, must be disinstalled to avoid conflicts.

**Comment by mrshu** [comment]
@nicor88 sure, that would make sense.

Let me try to put together a quick PR 🙂
