### ISSUE TITLE
dbt_valid_to date should be set to udpated_at column date value

### ISSUE THREAD

**Issue by rjhartings** [dbt-athena/dbt-athena#148]
The dbt_valid_to date should be set to udpated_at column date value not the current timestamp.

Per the documentation: https://docs.getdbt.com/docs/build/snapshots#snapshot-meta-fields

https://github.com/dbt-athena/dbt-athena/blob/5598286b0069a6cf4e630891286af0b3743149f9/dbt/include/athena/macros/materializations/snapshots/snapshot.sql#L213

`WHEN dbt_valid_to=CAST('9999-01-01' as timestamp) AND is_current_record=True
THEN {{ current_timestamp() }}`

This is causing overlaps in our valid date ranges.
Here are the meta data columns from one id:
id                                                                          updated_at                                   dbt_valid_from                          dbt_valid_to                              is_current_record
47a555a1-1455-481a-8937-d3cc03f02362  2021-09-02 13:58:09.961000  2021-09-02 13:58:09.961000  2023-02-14 20:05:44.433000  false
47a555a1-1455-481a-8937-d3cc03f02362  2021-09-03 13:57:59.941000  2021-09-03 13:57:59.941000  9999-01-01 00:00:00.000000  true

This was implemented with the following pull request:
#111

**Comment by nicor88** [comment]
@rjhartings would you mind to open a pr with the fix?
