### ISSUE TITLE
Add support for incremental_predicates

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#157]
Add support for incremental_predicates

More details can be find here: https://docs.getdbt.com/docs/build/incremental-models#about-incremental_predicates

Other adapters implementation: https://github.com/dbt-labs/dbt-core/pull/5702

**Comment by chrischin478** [comment]
@nicor88 I can start work on this. If there's something more urgent though let me know.

**Comment by chrischin478** [comment]
@nicor88 can close this now
