### ISSUE TITLE
Dash in schema name

### ISSUE THREAD

**Issue by chrischin478** [dbt-athena/dbt-athena#162]
When a schema name has a dash in it, e.g. `my-schema`, the following error is thrown when running a model:

`An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 9:8: mismatched input '-'. Expecting: 'OR', 'SCHEMA', 'TABLE', 'VIEW'`

When creating a table in the Athena UI the schema must be surrounded in back ticks to avoid this error, e.g. ```CREATE TABLE `my-schema`.table_name```. I tried setting my profiles.yml like so:

```schema: "`my-schema`"```

but I then received a permission error:

`[ErrorCategory:USER_ERROR, ErrorCode:PERMISSION_ERROR], Detail:Amazon Athena experienced a permission error. Please provide proper permission and submitting the query again...`

Is there any way around this or this just isn't supported at all?

**Comment by chrischin478** [comment]
This should be resolved by #152. I will confirm once the next release is deployed.

**Comment by nicor88** [comment]
Not sure exactly when we will release, alternatively you can try out to install the main branch.

**Comment by chrischin478** [comment]
Do you have a rough idea? Like less or more than a month? I'll try main
until then.

**Comment by chrischin478** [comment]
I installed dbt from main and when executing `dbt --version` I see `1.4.3`, yet I am still not able to create models with a schema name containing dashes. The same errors are encountered. I tried defining the profiles.yml file in three ways as follows:

```schema: my-schema```
```schema: "my-schema"```
```schema: "`my-schema`"```

**Comment by nicor88** [comment]
@chrischin478 I think that we might release withing the next weeks, there are enough contribution fixes.

Regarding this issue, have a read [here](https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html#schema-names)
> The only acceptable characters for database names, table names, and column names are lowercase letters, numbers, and the underscore character.

So for sure we could find some workarounds, but not sure that we should do it.

Couldn't you use the schema name directly in your model? the right working solution is escaping them with backticks?

**Comment by chrischin478** [comment]
I agree that the recommended naming does not include dashes but I've inherited this and am trying to work around it. New schema names are not an option either.



> Couldn't you use the schema name directly in your model?

I'm new to dbt so I'm trying to understand this recommendation. It's my understanding that the schema name for a model always comes from the profiles.yml file. Are you suggesting there's alternative way of passing the schema name for a new model?

**Comment by nicor88** [comment]
Schema name doesn't necessary need to be set in the profiles.yml, it can be setup per model level using `schema`.
Have a read here: https://docs.getdbt.com/docs/build/custom-schemas


The fact that creates statements and drop statements are not having consistent behavior on quoting makes implementing this a bit tricky.
I'm not sure if a custom macro will help you here, as we are dealing with some adapters' internals, and the relations are escaped accordingly.

@Jrmyy do you think that we can implement a workaround to support this?

**Comment by chrischin478** [comment]
I tried adding the schema config to the model directly, using the custom macro to prevent prefixing. As expected the same errors are encountered.

If it makes things simpler, I wanted to point out that when dropping a table the backticks don't need to be wrapped around both the schema and table like in AWS's documentation, just the schema is necessary.

**Comment by nicor88** [comment]
In your custom schema macro try to call `render_hive()` to your schema. That should help to escape the table properly at least on the ctas.

**Comment by chrischin478** [comment]
I'm not sure exactly how to call `render_hive()`. In the macro below I tried replacing line `{{ custom_schema_name | trim }}` with the following but had no luck:

`{{ custom_schema_name | trim }}.render_hive()`
`render_hive({{ custom_schema_name | trim }})`

```
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- else -%}

        {{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}
```

**Comment by nicor88** [comment]
@chrischin478 that's nice to hear, how did you fix that? Maybe we add a section in the Readme about this

**Comment by chrischin478** [comment]
@nicor88 The latest version of dbt-athena-community adapter fixes the issue, so there shouldn't be a need to add any special instructions.

**Comment by nicor88** [comment]
ah I thought that wasn't the case, so yeah, the rendering feature added fix that, let's close this then.
