### ISSUE TITLE
Setting `external_location` in CTAS conflicts with Athena workgroups that enforce centralised output

### ISSUE THREAD

**Issue by arryon** [dbt-athena/dbt-athena#176]
**Description**
AWS Athena Workgroup can be configured to override client settings, which enforces some workgroup-wide settings for all queries: https://docs.aws.amazon.com/athena/latest/ug/workgroups-settings-override.html

This feature can generate a few additional errors. For a full list of errors see: https://docs.aws.amazon.com/athena/latest/ug/workgroups-troubleshooting.html

In case of this package, whenever we create a materialised table with CTAS, it sets the `external_location` parameter to the S3 location where our materialised table should be created at https://github.com/dbt-athena/dbt-athena/blob/main/dbt/include/athena/macros/materializations/models/table/create_table_as.sql#L15

With the external location set, Athena operations fail with InvalidRequestException: `An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: The Create Table As Select query failed because it was submitted with an 'external_location' property to an Athena Workgroup that enforces a centralized output location for all queries. Please remove the 'external_location' property and resubmit the query.`

It does not matter whether the external location is actually a prefix within the existing S3 staging directory or not. What matters is that the setting is included while it is actually prohibited to be included at the Workgroup level.

A solution would be to modify the template so that `external_location` is only used whenever the `s3_data_dir` is set. Any other suggestions for fixing this for now?

**Related info**
- This issue was introduced in 1.3.2: https://github.com/dbt-athena/dbt-athena/blob/v1.3.2/dbt/include/athena/macros/materializations/models/table/create_table_as.sql#L19
- Version 1.3.1 works without issues
- Tested on 1.3.1, 1.3.2 and 1.4.4

**Comment by nicor88** [comment]
https://github.com/dbt-athena/dbt-athena/pull/160 can potentially fix this issue

**Comment by arryon** [comment]
That’s great! I should have checked the open PRs :). Happy to verify the fix as well if needed

**Comment by nicor88** [comment]
@arryon could you try the pr 160 and confirm that works as expected?

**Comment by arryon** [comment]
I will try some time today to test, will let you know asap as well @nicor88

**Comment by nicor88** [comment]
@arryon I merged the PR in main, so you have the changes in there directly. Let me know, otherwise we keep digging.

**Comment by arryon** [comment]
@nicor88 I just verified with `main`, can happily report that the issue was fixed by #160 🎊 . Thanks!
