### ISSUE TITLE
`get_columns_in_relation` crashes if table does not exist in Glue

### ISSUE THREAD

**Issue by owenprough-sift** [dbt-athena/dbt-athena#195]
# Problem
https://github.com/dbt-athena/dbt-athena/blob/458ebc1e255041fe72a5b0d2e8eeedc2448bd32f/dbt/adapters/athena/impl.py#L683-L686

Prior to #174, calling `adapter.get_columns_in_relation()` would query `information_schema.columns` and return nothing if the table did not exist in `information_schema`. As of #174, a non-existing table instead causes a runtime error/crash.

# Suggested Fix
When the table doesn't exist in Glue, return an empty list.

Also review other places in code updated by #174 to see if they are backwards-compatible with prior behavior and/or need to appropriately detect and handle boto3 errors.

# Workaround
Use `dbt-athena-community==1.4.1` instead of `1.4.2`.

# To Reproduce
## Sample model (`owen.sql`)
```
{% set column_names %}
  {{ adapter.get_columns_in_relation(this) }}
{% endset %}

select '{{column_names}}' as column_name_str
```

## Compiled output (pre-#174)
```
select '
  []
' as column_name_str
```

## Compiled output
None, because the project errors out during compilation
```
13:55:01  Unhandled error while executing model.test.owen
An error occurred (EntityNotFoundException) when calling the GetTable operation: Table owen not found.
```

**Comment by nicor88** [comment]
Good catch @owenprough-sift.
Are you willing to submit a pr? Something like that might work - we could add an helper function as well.

```
try:
    table = glue.get_table(DatabaseName='nicola', Name='my_table')
except ClientError as e:
    if e.response['Error']['Code'] == 'EntityNotFoundException':
        logger.debug('table not exist, catching the error')
        return []
    else:
        logger.error(e)
        raise e
```
