### ISSUE TITLE
Recent changes in current_timestamp macro break freshness tests

### ISSUE THREAD

**Issue by henriblancke** [dbt-athena/dbt-athena#197]
Since [this change](https://github.com/dbt-athena/dbt-athena/blame/458ebc1e255041fe72a5b0d2e8eeedc2448bd32f/dbt/include/athena/macros/utils/timestamps.sql#L6) our freshness tests have been failing with the below error:

```
Unknown type: timestamp(6)
```

**Comment by nicor88** [comment]
@henriblancke the issue could be related to thishttps://github.com/dbt-athena/dbt-athena/blob/458ebc1e255041fe72a5b0d2e8eeedc2448bd32f/dbt/include/athena/macros/utils/timestamps.sql#L6 as a workaround try to overwrite the macro in your local project, not 100% sure that the issue will be fixed

**Comment by nicor88** [comment]
this should be fixed by https://github.com/dbt-athena/dbt-athena/pull/235

**Comment by nicor88** [comment]
@henriblancke we just merged https://github.com/dbt-athena/dbt-athena/pull/235, can you confirm that the latest version from main resolve this issue?
