### ISSUE TITLE
Parameter validation failed: Invalid type for parameter WorkGroup

### ISSUE THREAD

**Issue by heuermh** [dbt-athena/dbt-athena#203]
After an update from `dbt-athena` to `dbt-athena-community` we're seeing this validation failure everywhere
```
Parameter validation failed:
Invalid type for parameter WorkGroup, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

I presume this is coming from a missing `work_group` configuration parameter, in `profiles/profiles.yml` perhaps?  This is annotated as Optional in README.md though.

**Comment by jessedobbelaere** [comment]
I also ran into this. It should be fixed with https://github.com/dbt-athena/dbt-athena/pull/194 (merged today but not released yet) 👍

**Comment by heuermh** [comment]
Cool, thank you @jessedobbelaere!

**Comment by nicor88** [comment]
@heuermh could you confirm that the latest main branch is not affected by this issue? If so we can close this :)
