### ISSUE TITLE
Lakeformation integration

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#22]
Add lakeformation integration to the adapter https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-athena-support-lake-formation-fine-grained-access-control/

Maybe as an idea, if lakeformation=true, the adapter take care of enabling lakeformation, and register the buckets used by the adapter on it.

**Comment by mattiamatrix** [comment]
Hey @nicor88, what kind of integration do you have in mind?

I am not sure if this adapter should modify any Lake Formation settings. Only Data lake administrators (or Lake Formation admins in form of IAM User or IAM Role) should be able to make changes.

I see dbt "jobs" as consumers of the data platform where settings, data locations and permissions on DBs and tables are provided as part of the data platform provisioning.

**Comment by nicor88** [comment]
@mattiamatrix in the context of data mesh, with a centralized catalog I agree with you. I was thinking that the adapter could have some little helpers (disabled by default), that allows to register the s3 bucket used by dbt in lakeforkation.

**Comment by mattiamatrix** [comment]
I see the concept of [grants](https://docs.getdbt.com/reference/resource-configs/grants) already exists. It might be extended to support buckets too

**Comment by thenaturalist** [comment]
@mattiamatrix 
> I am not sure if this adapter should modify any Lake Formation settings. Only Data lake administrators (or Lake Formation admins in form of IAM User or IAM Role) should be able to make changes.

I would not fully agree with your statement. 

Lakeformation offers detailed permissions settings, i.e. permissions given to non-administrators can be given just as is or be given as grantable, so the role itself can grant the exact same scope at max which it was granted itself. 

> I see dbt "jobs" as consumers of the data platform where settings, data locations and permissions on DBs and tables are provided as part of the data platform provisioning.

I would also disagree with this statement slightly. The main determinant whether something falls into the platform or rather the "jobs" category is frequency of change. 

So for example, I would put datalake locations, s3 buckets, firmly into the platform domain and as something _not_ managed by dbt. There are fundamental security aspects, the N of managed objects is probably small and the concept of a location works per se pretty independent of if and how data is transformed after ingestion. 

This is not the case with grants, to the concept you linked to @mattiamatrix. 

I see this much closer and useful when managed by dbt for a couple of reasons:
- Grants on a dataset are a very closely related artefact of a dbt job, hence they are implemented for the other platforms
- Managing grants somewhere else, in Terraform, is rather cumbersome, both when it comes to coding, as well as the code living in two completely separate places
- Typically, you'd want a potentially large number N of grants if the datalake is used and again, paired with frequent changes, leading to a high number of frequent changes. Again, if the changes live in two places, deploying them accurately together is cumbersome
- I'd see very basic grants (who is datalake admin, which roles have what kind of maximum permissions) as manageable by the data platform team in Terraform. These base settings are expected to _not_ change frequently
- Operational changes within this scope should be manageable via Lakeformation within dbt

This is a rough outlook on my thoughts on the topic. 
Happy to discuss further and I'd also ping the community to ideally get some more perspectives to make the tradeoffs and prio clearer. 

What do you think @mattiamatrix @nicor88 ?

**Comment by dacreify** [comment]
For using Lake Formation Tag Based Access Controls (TBAC) I think encoding the tags in DBT YAML could be really useful. i.e. Categorizing the data produced by the model to drive the appropriate grants elsewhere. The TBAC grants themselves and other infra setup does seem better managed in TF.

**Comment by nicor88** [comment]
@dacreify I totally agree with you, the key is to:
* let dbt-athena create "schemas" aka databases and then tag them based on what is specified from in a yml definition
* as tables inherit from databases the tags, the only case where we need to re-tag a table is when its tags is different from the parent, this can be done with a post hook macro

In both case to do this operations, the role used for dbt needs to be have associate tag permissions in lf.

**Comment by nicor88** [comment]
Groundwork done in this PR: https://github.com/dbt-athena/dbt-athena/pull/159

What is missing is the possibility to add tags to specific columns

**Comment by nicor88** [comment]
Closing this one.

The most relevant work has been implemented:
* dbt athena nows supports assigning tags to database, tables and columns
* dbt athena supports "overwriting" inherited tags from the parent relations, e.g. if a table inherits tags from the parent db, we can overwrite them using dbt.

At the momement there is no plan for dbt-athena to provide access control for the AWS principals, this means that you cannot use dbt-athena to grant select/insert/delete or create/drop in tables and databases with specific tags.
It's recommended to have such permission control using other tooling e.g. terraform/cdk or boto3.
