### ISSUE TITLE
Delete records based on condition for Iceberg MERGE strategy

### ISSUE THREAD

**Issue by Jrmyy** [dbt-athena/dbt-athena#230]
👋🏻  Hello

The [MERGE](https://trino.io/docs/current/sql/merge.html#examples) statement in Trino enables to delete some records based on condition. Would it be possible to make it available in the `merge` strategy. For instance I was thinking of something like that:

```sql
{{ config(
  materialized='incremental',
  incremental_strategy='merge',
  table_type='iceberg',
  unique_key='id',
  delete_condition='src.is_deleted'
}}

SELECT
  a,
  b,
  ts,
  {% if is_incremental() %}
  is_deleted
  {% endif %}
FROM {{ ref('my_model') }}
{% if is_incremental() %}
WHERE ts > (SELECT max(ts) FROM {{ this }}
{% endif %}
```

Of course it would need documentation on how it works and maybe some limitations like it should only be condition on the src table, etc...

**Comment by nicor88** [comment]
How about letting the user pass the full merge condition in case of delete
> WHEN MATCHED delete_condition 
    THEN DELETE

For example from cdc records from debrezium the user will pass something like `src.op='d'`
Is that what you have in mind @Jrmyy?

**Comment by Jrmyy** [comment]
That is exactly what I have in mind.

**Comment by nicor88** [comment]
Adding this conversation in slack for reference: https://getdbt.slack.com/archives/C013MLFR7BQ/p1680007031994569
