### ISSUE TITLE
Version 1.4.3. breaks `docs generate` because of missing `TableType` parameter.

### ISSUE THREAD

**Issue by junckritter** [dbt-athena/dbt-athena#240]
Hello, we are having issues with generating docs with the versions 1.4.2 and 1.4.3, although `dbt run` and `dbt test` passes without problem. The command fails with 
```
Encountered an error while generating catalog: 'TableType'
dbt encountered 1 failure while writing the catalog
```
but the only connected messages in the log are such as :
```
[0m11:37:35.551755 [debug] [ThreadPool]: Athena adapter: Table 'abc_xyz' has no TableType attribute - Ignoring
```
for 5 (of 140) our tables. No other `warn` or `error` message in the log.
Also, we see no difference in Athena settings for these particular tables.

Used libraries:
 * boto3==1.26.101
 * pyathena==2.24.0
 * dbt-core==1.4.5

Revert to version 1.4.1 helps - it passes without any issue.

**Comment by nicor88** [comment]
@junckritter Could you run `dbt -d docs generate`? and copy the output?
The issue could be releate to this line: https://github.com/dbt-athena/dbt-athena/pull/174/files#diff-629c67ee6aeee24555537b786b7560cbf4d17496c1388aa932de34081c76f668R254

Could you tell us more about the tables where it breaks?
Ideally for those table you  run this:
```
import boto3
glue = boto3.client('glue')
table = glue.client.get_table(
    DatabaseName='your_db',
    Name='your_table_name'
) 
```
and the you copy the content  of `table` (trimming out sensitive data of coure), that could help us to find it more about the table that we are dealing with. Many thanks!

**Comment by junckritter** [comment]
I can confirm that the param 'TableType' is missing in the received dictionary, unlike for other our tables. The probable cause is way of the creation for problematic tables - they were created from the code using API (i.e. boto3). All the others were created either via Glue Crawler or with Athena's `CREATE TABLE` query. It is even mentioned in the [docs](https://docs.aws.amazon.com/athena/latest/ug/creating-tables.html) that this param would be missing when the table is created via API.
