### ISSUE TITLE
New hive-style quote impl leaks into libs that use dbt-athena

### ISSUE THREAD

**Issue by brabster** [dbt-athena/dbt-athena#277]
I've been trying to sort out a [PR to enable external table support for Athena over in dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables/pull/203). I've hit a minor-ish problem in that I've had to use the new `render_hive()` function to get the quoting right on these DDL statements. ([relevant commit](https://github.com/dbt-labs/dbt-external-tables/pull/203/commits/94ed9244d672014a27b560e7407ad31b778f3f09))

That does work but it does make supporting versions of dbt-athena prior to 1.4.1 tricky - I've just not bothered for now - but it also suggests a potentially troublesome bit of coupling. I'm no dbt expert so maybe there's a better way of getting the right quoting for these statements?

**Comment by sacundim** [comment]
This looks related to my ticket: https://github.com/dbt-athena/dbt-athena/issues/182

**Comment by nicor88** [comment]
Let's use #182 instead, that seems more descriptive.
