### ISSUE TITLE
Possibility to use athena via CalledVia option - no glue api calls/ no s3 calls

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#302]
In order to support the CalledVia option for athena, we need to introduce new flags that allow a native behavior to create/insert data into tables.

In order to do so we need to have additional flags:
-  native_drop: table is dropped via "drop" DML in athena, in case of iceberg we use the native s3 path dropping, as iceber tables are managed
~- use_information_schema: allow to fetch glue tables details via information schema, pretty much means merging what was done in https://github.com/dbt-athena/dbt-athena/pull/174 with 2 behaviours~ 
- allow seeds without s3 upload -> https://github.com/dbt-athena/dbt-athena/pull/283, flag name to agree

Regarding the usage of information schema, after discussing with @brabste we agreed that we use of information schema is not necessary, as we can use glue apis - and we avoid still direct access to S3 data.

**Comment by brabster** [comment]
Mentioned in athena infra, closing.
