### ISSUE TITLE
Attempts to rename table but invalid syntax in Athena

### ISSUE THREAD

**Issue by brabster** [dbt-athena/dbt-athena#331]
Trying to upgrade to latest version (hi, me again, following fix of native_drop and seed_by_insert...). dbt run against a model with materialization=table is erroring when running `alter table a.b.c rename to d.e`. Offending code seems to be [here](https://github.com/dbt-athena/dbt-athena/blame/90eecf1fcde2994caea9f6ead316bf54ad6af137/dbt/include/athena/macros/adapters/relation.sql#L15)

- Iceberg table, working fine on older version, no config changes (other than adding native_drop)
 - [Athena docs](https://docs.aws.amazon.com/athena/latest/ug/unsupported-ddl.html) say `rename to` syntax not supported, weird?!
 - [This documentation](https://dbt-athena.github.io/docs/migration/UPGRADE-1.5) may be related but seems like the ha behaviour is the default and is broken?

**Comment by svdimchenko** [comment]
Hi @brabster! Could you add model example where you have problem ? it seems that current implementation for table materialisation works in following way:
1. check if table_type is hive and then provide custom logic for HA strategy
2. for all other table_types (including iceberg), HA strategy is enabled by default.
Did I miss smth ?

**Comment by Jrmyy** [comment]
To add further explanation:
1. High availability is supported for both Hive and Iceberg tables and is the only solution for Iceberg tables using the RENAME command
2. We check the table_type and act accordingly
