### ISSUE TITLE
Add data_scanned_in_bytes to adapter response

### ISSUE THREAD

**Issue by jurgispods** [dbt-athena/dbt-athena#335]
It would be great to include the amount of data scanned by Athena in the adapter response, similar to what [`dbt-bigquery`](https://github.com/dbt-labs/dbt-bigquery/blob/1.1.latest/dbt/adapters/bigquery/connections.py#L86-L88) is doing. This would allow for parsing the `run_results.json` after a DBT run, calculate the sum of data scanned and monitor the associated cost.

Do you have any objections about adding this feature? If not, I would be willing to implement it.

**Comment by Jrmyy** [comment]
Hello 👋🏻 
This seems a really good feature ! You can give it a try if you want 🙂
