### ISSUE TITLE
IAM permissions documentation may be missing glue:CreateDatabase

### ISSUE THREAD

**Issue by jeancochrane** [dbt-athena/dbt-athena#364]
The [IAM permissions documentation](https://dbt-athena.github.io/docs/getting-started/prerequisites/iam-permissions#glue-iam-permissions) lists the following required permissions for Glue:

> ## Glue IAM permissions
> dbt-athena uses the AWS Glue API to fetch metadata. You will need to set these permissions on the Glue databases you are reading from:
>
> ```
> "glue:GetDatabase",
> "glue:GetDatabases",
> "glue:GetTable",
> "glue:GetTables",
> "glue:GetPartition",
> "glue:GetPartitions",
> ```
>You will need these permissions on the glue databases you are writing to:
>
> ```
> "glue:GetDatabase",
> "glue:GetDatabases",
> "glue:GetTable",
> "glue:GetTables",
> "glue:GetPartition",
> "glue:GetPartitions",
> "glue:BatchCreatePartition",
> "glue:BatchUpdatePartition",
> "glue:BatchDeletePartition",
> "glue:BatchDeleteTable",
> "glue:BatchDeleteTableVersion",
> "glue:CreatePartition",
> "glue:UpdatePartition",
> "glue:DeletePartition",
> "glue:CreateTable",
> "glue:UpdateTable",
> "glue:DeleteTable",
> "glue:DeleteTableVersion",
> ```

However, with these permissions in place for the role that runs our CI, we're seeing a permissions error message on `dbt run` when dbt-athena attempts to create a schema that does not exist:

```console
$ dbt --debug run --target ci
20:46:11  Creating schema "database: "awsdatacatalog"
schema: "ci_jeancochrane31_default"

20:46:11  Using athena connection "create_awsdatacatalog_ci_jeancochrane31_default"
20:46:11  On create_awsdatacatalog_ci_jeancochrane31_default: -- /* {"app": "dbt", "dbt_version": "1.5.4", "profile_name": "athena", "target_name": "ci", "connection_name": "create_awsdatacatalog_ci_jeancochrane31_default"} */
create schema if not exists `awsdatacatalog`.`ci_jeancochrane31_default`

20:46:11  Opening a new connection, currently in state closed
20:46:12  Athena adapter: Query state is: QUEUED. Sleeping for 1.0...
20:46:13  Athena adapter: Query state is: RUNNING. Sleeping for 1.0...

Athena adapter: Error running SQL: macro create_schema
20:47:35  On create_awsdatacatalog_ci_jeancochrane31_default: Close
20:47:36  Athena adapter: Error running SQL: -- /* {"app": "dbt", "dbt_version": "1.5.4", "profile_name": "athena", "target_name": "ci", "connection_name": "create_awsdatacatalog_ci_jeancochrane31_default"} */
create schema if not exists `awsdatacatalog`.`ci_jeancochrane31_default`

20:47:36  Connection 'create_awsdatacatalog_ci_jeancochrane31_default' was properly closed.
20:47:36  
20:47:36  Finished running  in 0 hours 1 minutes and 25.29 seconds (85.29s).
20:47:36  Encountered an error:
Runtime Error
  Runtime Error
    [ErrorCategory:USER_ERROR, ErrorCode:PERMISSION_ERROR], Detail:Amazon Athena experienced a permission error. Please provide proper permission and submitting the query again. If the issue reoccurs, contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience., Message:Amazon Athena experienced a permission error. Please provide proper permission and submitting the query again. If the issue reoccurs, contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience.
20:47:36  Command `dbt run` failed at 20:47:36.221700 after 87.46 seconds
```

Adding `glue:CreateDatabase` permissions to the IAM role policy resolved the error.

Perhaps the documentation assumes that we will not need to create a database, which could make sense given that the [AWS resources page](https://dbt-athena.github.io/docs/getting-started/prerequisites/aws-resources) lists creating a database as a prerequisite. But since dbt-athena has the power to create a database and will do so if one does not exist, it seems confusing to me that it isn't part of the recommended permissions, especially as someone who is not an expert on Glue permissions.

What do you think? Would you be open to a patch that tweaks the documentation to add this permission, or would you prefer that the recommended permissions be locked down as tightly as possible given that the prerequisites imply that a database should already exist?

**Comment by jessedobbelaere** [comment]
In dev environments and PR's we also let dbt take care of creating databases 👍 (e.g. `dev_jessedobbelaere_*` or `dev_<branch_name>`) so I guess it makes sense to document this permission indeed
