### ISSUE TITLE
Add support for seed file upload with enforced ACL/SSE KMS keys

### ISSUE THREAD

**Issue by linkerzx** [dbt-athena/dbt-athena#389]
With the introduction of a new method to [upload files to S3 in DBT-Athena 1.4.2](https://github.com/dbt-athena/dbt-athena/commit/31e20a49a5d715f435a75c385b31057e3328c98f#diff-629c67ee6aeee24555537b7[…]c1388aa932de34081c76f668R255), we have been facing issues with the upload of seed files receiving the following error:
`botocore.exceptions.ClientError: An error occured (AccessDenied) when calling the PutObject operation: Access Denied`

The error stems from the upload_file method requiring  additional keyword arguments when working with Enforced ACL/KMS. 
When updating the upload_file command to: 
`s3_client.upload_file(tmpfile, bucket, object_name, ExtraArgs={'ACL': 'bucket-owner-full-control', 'SSEKMSKeyId':'<myKMSkey>', 'ServerSideEncryption': 'aws:kms'})`

DBT works as expected, and we are able to upload the seed files onto S3/Athena.

We would like to have a way to define these extra arguments as part of the DBT profile.

**Comment by linkerzx** [comment]
Hi @nicor88 , we have an S3 bucket key defined - however our organization enforces a strict deny in case of missing s3:x-amz-server-side-encryption or s3:x-amz-acl variables in the s3:PutObject calls.

**Comment by nicor88** [comment]
Ah I see - thanks for the clarification. We can consider then as stated above- we can add extra args based on an extra profile parameter.

**Comment by linkerzx** [comment]
Still in draft but would something like this work: 
https://github.com/dbt-athena/dbt-athena/pull/397/files ?
