### ISSUE TITLE
dbt insert_overwrite is not working when overwriting partition

### ISSUE THREAD

**Issue by selmanmoon** [dbt-athena/dbt-athena#413]
Hi,

I'm using the example model below that I found early in this repo from @nicor88 ;

```
{{ config(
    incremental_strategy='insert_overwrite',
    table_type = 'hive',
    s3_data_naming = 'schema_table',
    partitioned_by=['report_date'],
    format='parquet',
    materialized = 'incremental'
) }}

SELECT
    999999 AS cost,
    cast(t.ts AS date) as report_date
FROM unnest(sequence(cast('2022-10-01' AS date), cast('2022-11-01' AS date), INTERVAL '1' Day)) AS t(ts)

```
when I run this model the first time it's creating table successfully, when I run the same model again it's deleting the partitions but not able to overwrite new partitions from _tmp table. Below command is failing on Athena;

```
-- /* {"app": "dbt", "dbt_version": "1.5.2", "profile_name": "xyz", "target_name": "xyz", "node_id": "model.table"} */

    
    insert into "AwsDataCatalog"."schema1"."table1" ("cost", "report_date")
    (
       select "cost", "report_date"
       from "AwsDataCatalog"."schema1"."table1__dbt_tmp"
```

Error msg;

```
HIVE_METASTORE_ERROR: Database cannot be a link for this operation when called on a table. 
(Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 50f432e8-ebe3-420a-9c2d-c143c3ec2c45; Proxy: null). 
If a data manifest file was generated at 's3://xyz-dbt-query-results-<account_id>-ef-int-eu-west-1/output/b92060af-5d54-4f4f-a04e-724cf082d13f-manifest.csv', 
you may need to manually clean the data from locations specified in the manifest. 
Athena will not delete data in your account.
```

Any suggestion is appreciated as I'm following the documentation quite closely and tried many workaround still not able to fix this issue. Thanks alot!

**Comment by nicor88** [comment]
@selmanmoon I just tried now with the latest version of the adapter 1.6.1.
and worked for me.
Specifically I run this
```
{{ config(
    incremental_strategy='insert_overwrite',
    table_type = 'hive',
    s3_data_naming = 'schema_table',
    partitioned_by=['report_date'],
    format='parquet',
    materialized = 'incremental'
) }}

select
    999999 as cost,
    cast(t.ts as date) as report_date
from unnest(sequence(cast('2022-10-01' as date), cast('2022-11-01' as date), interval '1' day)) AS t(ts)
```
looking at the error seems that you are trying to use a database link to persist your model:
`Database cannot be a link for this operation when called on a table. ` - are you using database links in glue?

**Comment by selmanmoon** [comment]
Thanks @nicor88  it's working when I use default database in the account, but fails when I use a target database which is in another account, seems like database permission issue or something else, I will check more detail, but we can close this issue meanwhile, thanks again!.
