### ISSUE TITLE
Incremental dbt logic is really slow

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#418]
Hi,

I don't think it is an issue with the dbt adapter but somehow if I write my incremental logic with hardcoded dates Athena scans what it needs to scan and it takes only a few minutes.
If I use the proposed dbt logic with getting the `min(xyz_date) from {{ this }}`  or max - depending if we go into the past or from past to now - it takes ages and Athena starts to scan GBs of data.

I tried to first get the dates in CTEs and query the dates from there but it doesn't make a difference.

Are subqueries in `WHERE`-Clauses in Athena not possible? As I said - if do not use a subquery but just `my_date between date_add('month', -2, date '2023-01-01') and date '2023-03-01'` it just works. But I really do not want to use variables or hardcode this...

We are using HIVE format.

```
{{ config(
    materialized='incremental',
    table_type='hive',
    partitioned_by=['my_id', 'my_date', 'my_code']
) }}

with

my_data as (
    select
        *
    from {{ ref('my_tr_view') }}
    where
    {% if is_incremental() %}
        my_date between date_add('month', -2, (select min(my_date) from {{ this }})) and (select min(my_date) from {{ this }})
    {% else %}
        my_date between date_add('month', -1, current_date) and current_date
    {% endif %}
),

final as (select * from my_data)

select * from final
```

**Comment by CommonCrisis** [comment]
You saved my day!
I tried inner joins, query on the meta data - boy I wish I would be allowed to use a proper Data Warehouse.

Just out of curiosity: Why are u using Athena?

**Comment by nicor88** [comment]
We are using dbt-athena mostly because of:
- cost
- not being vendor or technologic lock - thanks to Iceberg it's possible to change the the engine on top your data. See also what Snowflake introcuded in preview recently, it allows customers to save the data as iceberg in their Object storage

**Comment by CommonCrisis** [comment]
Okay thx :)
