### ISSUE TITLE
Incremental model many small files

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#419]
Hi,

maybe I am missing something - but is it possible to force Glue to save multiple small files into one big file?
We are using HIVE tables.

I have 3 partitions and then in there 20 or so files 50 KB files. To reduce the GET requests only having one would be ideal.
Now: `/par_1/par_2/par_3/` --> many many files

Ideal: `/par_1/par_2/par_3/my_file_with_all_data.parquet`

I only filter on my partitions anyways - so having a lot of small files just increases the costs.

Thx!

**Comment by nicor88** [comment]
The amount of files are related to the amount of workers that athena uses under the hood, therefore hard to control. 
One workaround with hive it's to use bucketing set to 1, but I'm not sure if it works with partitions, I only used for not partitioned tables. 

Alternatively you can switch to iceberg, and you can optimize your table as a post hook (I'm using this currely). The optimize function serves exactly to do what you describe : compact multiple objects into one (or multiple) based on a config that I don't remember (default max size per file is 512MB).

**Comment by CommonCrisis** [comment]
Okay great - I will try iceberg then :)

**Comment by nicor88** [comment]
@CommonCrisis did you manage to solve the small files issue using iceberg?

**Comment by CommonCrisis** [comment]
I did a simple test - and to be honest Iceberg even creates more than Hive^^

Bucketing does not work at all with incremental models even if it would solve the issue (but Athea docu already says that INSERT INTO is not supported).

I will check with more data and update the issue. Maybe there is another workaround cause these GET-Requests are just a pain to pay for.

**Comment by nicor88** [comment]
There are few points to be aware when working with iceberg:
* you need to run optimize, that will compact the objects in bigger ones. Optimize produce a new snapshot, that means that old data is retained 
* after an optimize procedure you might want to run vacuum, that expire older snapshot
* do not look the s3 path where you have your data, but use instead this query ` select distinct "$path" from your table`. As mentioned above your data folder can contains multiple snapshots, that's why you have the feeling that iceberg is producing more fikes

**Comment by CommonCrisis** [comment]
Thanks for the hint with the snapshots - I just used the S3 count logic (used to due to hive). My current config already looks like this:

```
{{ config(
    materialized='incremental',
    table_type='iceberg',
    partitioned_by=['col_1', 'col_2', 'col_3'],
    incremental_strategy = 'merge',
    unique_key = 'my_unique_key_col',
    s3_data_naming = 'schema_table_unique',
    on_schema_change='fail',
    post_hook=['OPTIMIZE {{ this }} REWRITE DATA USING BIN_PACK', 'VACUUM {{ this }}']
) }}

with

[...]
```

I will still see if there is any way to merge these hive files just in case someone needs to stick to HIVE table format.

**Comment by CommonCrisis** [comment]
Hmm closing this - I don't think it is possible currently with Hive.
