### ISSUE TITLE
Invalid incremental strategy provided: None

### ISSUE THREAD

**Issue by jessedobbelaere** [dbt-athena/dbt-athena#42]
I noticed this in a couple of my projects already, after switching to dbt `1.3.0` and `1.3.1`

Given a simple model with this config block:

```jinja
{{
    config(materialized='incremental')
}}
```

When I deploy this model using dbt, it throws:

```
23:09:13.423010 [error] [MainThread]: Compilation Error in model event_login (models/silver/content/XXX.sql)
23:09:13.423138 [error] [MainThread]:   Invalid incremental strategy provided: None
23:09:13.423268 [error] [MainThread]:       Expected one of: 'append', 'insert_overwrite'
23:09:13.423403 [error] [MainThread]:   
23:09:13.423529 [error] [MainThread]:   > in macro validate_get_incremental_strategy (macros/materializations/models/incremental/helpers.sql)
23:09:13.423653 [error] [MainThread]:   > called by macro materialization_incremental_athena (macros/materializations/models/incremental/incremental.sql)
23:09:13.423777 [error] [MainThread]:   > called by model event_login (models/silver/content/XXX.sql)
```

**I can reproduce in both the Tomme athena adapter and this new dbt-athena adapter, when I'm using dbt 1.3.1.** 
Therefore, it seems like something that was introduced with dbt 1.3?  When I switch to `dbt-core==1.2.1` it works fine. However, I can't find something related in the dbt 1.3.0 or 1.3.1 release changelog...

It's weird because we set `insert_overwrite` as a **default** here: https://github.com/dbt-athena/dbt-athena/blob/91f793f1150bf316780cffcf6ef934a27ec4fbd2/dbt/include/athena/macros/materializations/models/incremental/incremental.sql#L11-L12

And then we call `validate_get_incremental_strategy` which throws the error. 

When I debug the `incremental.sql` file:

```
{% set raw_strategy = config.get('incremental_strategy', default='insert_overwrite') %}
{{ log("RAW STRATEGY: " ~ raw_strategy, True) }}
{% set strategy = validate_get_incremental_strategy(raw_strategy) %}
``` 

Then the console prints `RAW STRATEGY: None` when I run dbt. Somehow the default is not being applied since dbt 1.3?!

The quick fix is to add an explicit `incremental_strategy='insert_overwrite'` in the model config block. However, I'd like to highlight this issue because the default stopped working in this macro... 🙏

**Comment by nicor88** [comment]
that's an odd error, as `raw_strategy` should fallback to  `insert_overwrite` when not set. Definitely need to be investigated, thanks for reporting.
