### ISSUE TITLE
Use glue APIs instead of information schema

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#44]
Based on https://github.com/dbt-athena/dbt-athena/pull/4#issuecomment-1305576711

Implementation should be covered here https://github.com/northvolt/dbt-athena/commit/49c7111eab13182ec27c3b7e11d7453ab005c550

Using Glue API is better as faster and should allow multi-threading.

# TODO
- [x] Use glue api instead of information schema
- [x] Use delete table from glue api - consider to do for Iceberg as well, as timeout lead to not having full deleted data. Before dropping pick the location from glue catalog.

**Comment by nicor88** [comment]
@jessedobbelaere FYI.

**Comment by chrischin478** [comment]
@nicor88 I'll make an attempt at the Glue API delete

**Comment by Jrmyy** [comment]
👋🏻 Hello @chrischin478 
Have you been able to work on this issue ?
Otherwise, if don't have time, I can take since I developed the part of about table info 🙂 .

**Comment by chrischin478** [comment]
@Jrmyy still giving it a crack. When should this be completed by? I don't want to take too long with this.

**Comment by nicor88** [comment]
we are planning to close this for the 1.4.4 milestone, that should happen in the next week.
