### ISSUE TITLE
Window functions ignoring partitions

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#448]
Hi,

I tried to filter out some duplicates in an intermediate model to then use iceberg incremental in my fct model on the filtered data.
Do you know why Athena ignores my incremental where clause logic in my fct model and scanns like everything in my intermediate model. Is there a way to inject the filter parameters (date, name, whatever) to my parent intermediate model using dbt?

Thanks! 

fct:

```sql
{{ config ... }}

select * from my_intermediate_model
where rn = 1
{% if is_incremental() %}
and col_1 = xyz and col_2 = abc
{% endif %}
```

my_intermediate_model:

```sql
select 
col_1,
col_2,
col_3,
row_number() OVER (PARTITION BY col_3) AS rn
from my_source
```

**Comment by Jrmyy** [comment]
👋🏻 Hello

Thanks for your issue. I would need more information to understand the problem. Can you provide the materalization / config of both models (for instance if there is any partitonning, etc)

**Comment by CommonCrisis** [comment]
Okay let me give you an example:

I have a src table on top a staging view and on top of this is a transformation view that contains:

```sql
with

smaller_table as (
    select
        *
    from {{ ref("stg_view") }}
    where not abc= 'done'
),

rank_transfer_time_for_each_xyz as (
    select
        *,
        rank() over (partition by abc_id order by my_timestamp desc) as abc_time_rank_desc
    from smaller_table
),

final as (
    select
        *
    from rank_transfer_time_for_each_xyz 
)

select *
from final
```

Okay nothing fancy here I just want to rank based on an id ordered by an timestamp.

Now I have my marts model thats for this purpose a view and I need to filter the data down from there (this marts model is used in a BI Tool).
Here  we of course filter on partitioned  columns in this case on my_date so I only want the calculation of my transformation model based on the date range I provide with the where clause:

```sql
with

tr_model_filter as (
    select
        ...
        -- partition column
        my_date
    from {{ ref("tr_rank_transfer_time_for_each_xyz ") }}
where my_date between date '2023-01-01' and date '2023-01-31'
),

final as (
    select *
    from tr_model_filter 
)

select *
from final
```

The problem is that the transformation model completely ignores the where clause and scans all data of my source.

Any idea how to fix this? Somehow I need to inject the where clause into my transformation model using dbt...

**Comment by nicor88** [comment]
> I have my marts model thats for this purpose a view and I need to filter the data down from there (this marts model is used in a BI Tool).
that's get tricky, as your mart model is based on a view that run on top of a table that is partitioned, that could get tricky and partition pruning might not work.

Did you tried to:
* persist your mart model as partitioned table? (consider to use hive and ha=true)
  * when doing so, could you check that the queries issued by your BI tools are scanning less data?

**Comment by svdimchenko** [comment]
@CommonCrisis I believe you have 2 options for that case:

1. materialise the mart table (as @nicor88 has mentioned) and connect to it using BI tool to get benefits from partition pruning
2. build kind of semantic layer on top of you stg table which will be responsible to build queries dynamically. To be honest, it's not simple way but you may try [cube.dev](https://cube.dev/) for that.

And finally I don't think that the issue requires any changes in current adapter, available functionality should allow you to materialise the optimised mart.

**Comment by CommonCrisis** [comment]
I will give it a shot! Thanks!
