### ISSUE TITLE
Hive table ha:true table partition issue

### ISSUE THREAD

**Issue by lrousset** [dbt-athena/dbt-athena#464]
Attempting to run an `ha``table` with a unique location set we can see the following issues:

- Looking at the current table version, some partitions refers to the previous table version
- Some partitions are entirely missing in glue ( but present in s3 )

There are silent failures being noticed in CloudTrail `BatchCreatePartition` such as:

                "errorDetail": {
                    "errorCode": "AlreadyExistsException",
                    "errorMessage": "Partition already exists."
                }

**Comment by nicor88** [comment]
@lrousset please confirm if this issue is resolved with https://github.com/dbt-athena/dbt-athena/pull/465

**Comment by lrousset** [comment]
All good on our side, issue seems resolved!

**Comment by nicor88** [comment]
Thanks @lrousset for the validation on this issue, much appreciated.
