### ISSUE TITLE
Incremental strategy inefficient/fails for very large tables

### ISSUE THREAD

**Issue by lukealexmiller** [dbt-athena/dbt-athena#471]
### Problem:
I have very long-running materialisations of tables with >1B rows.
A solution would be to switch to incremental materialisation and partition the tables, in our case this would be by `year`, `month`, `day`. The underlying source data is already partitioned like this, which helps. The idea being that querying subsets of data is more efficient.

It's great that #360 solves for the 100 partition limit on Athena (👏), but it seems like #405 requires that we are able to materialise the non-partitioned table.

Given that we can't (efficiently or in some cases at all due to OOM) materialise the non-partitioned table, what are my options? 
As I see it there are a couple of hacky solutions:
1. Materialise sub-tables, e.g. create incrementally-materialised sub-tables for each `year` and union them together.
2. Manually (or via a macro) loop through each of the most coarse-grained partitions (in this case `year`, so the query would have an additional filter `AND year = 2015`), adding partitions until all fine-grained partitions (`month` and `day`) have been added before proceeding to the next.

### Questions:
1. Is there a solution for this problem that the adapter already supports that I've missed? 
2. If this is a common problem for very large datasets, can/should this be supported by modifying how incremental materialisation is implemented in the adapter?

Thanks in advance for any advice!

**Comment by nicor88** [comment]
I believe that the best shot here is to use `insert_by_period`, described here: https://gist.github.com/jessedobbelaere/6fdb593f9e2cc732e9f142c56c9bac87
Pretty much using insert_by_period you run your statement incrementally for specified periods, breaking down the computation.

Alternatively, you can consider adding `variables`  to inject yearly filter, and run your model manually for those really heavy tables.

e.g. 

dbt run -s --vars `{"start_year":2015, "end_year": "2015", "backfilling": true}`, then reference in your model like this

```
where
{% if var(backfilling, 'false')  %}
  year >= {{ var(start_year) }} and year <=  {{ var(end_year) }} 
{% endif %}
```
It's is a light version of what insert_by_period can do for you.

**Comment by lukealexmiller** [comment]
Thanks @nicor88, this macro does exactly what I wanted!

**Comment by CommonCrisis** [comment]
I have another question regarding this macro.

I'm running into the `HIVE_TOO_MANY_OPEN_PARTITIONS` problem we all know and love.
But afaik the macro is calling `incremental_insert` that is adjusted in the athena adapter to use the `get_partition_batches` logic, right?

So is the macro using something else for `incremental_insert` or why do I run into the  `HIVE_TOO_MANY_OPEN_PARTITIONS` error?

I just try to understand so maybe we could implement this logic into the adapter...
