### ISSUE TITLE
Switching from hive table to iceberg table lead to failure

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#478]
I have some tables that are hive/parquet, and when trying to use iceberg table it fails to create the table as iceberg.

Somehow the original table is not dropped and re-created as iceberg, and given that the final materialization is iceberg, it try to do a rename, that of course don't work.

## How to reproduce

Run first this model
```
{{ config(
        materialized='table',
        partitioned_by=['date_column'],
        force_batch_insert=true,
        table_type='hive',
        ha=false
    )
}}

select
    random() as rnd,
    cast(date_column as date) as date_column
from (
    values (
        sequence(from_iso8601_date('2023-01-01'), from_iso8601_date('2023-07-31'), interval '1' day)
    )
) as t1(date_array)
cross join unnest(date_array) as t2(date_column)
```

Switch the model to the following:
```
{{ config(
        materialized='table',
        partitioned_by=['date_column'],
        force_batch_insert=true,
        table_type='iceberg'
    )
}}

select
    random() as rnd,
    cast(date_column as date) as date_column
from (
    values (
        sequence(from_iso8601_date('2023-01-01'), from_iso8601_date('2023-07-31'), interval '1' day)
    )
) as t1(date_array)
cross join unnest(date_array) as t2(date_column)
```
The underlying tmp table is created as iceberg,  but considering that the old original table is hive, iceberg materialization try to do a renaming that don't work.

## Proposed fixes
1. When using iceberg check if the original table exists, and if it's hive, drop it and then rename, instead of renaming the original table to backup.
2. Alternatively, we do a full refresh with iceberg we can always drop the original table, then avoid to use the rename. This will be a cleaner solution.

**Comment by mycaule** [comment]
There is also the small annoying thing that you need to manually deal with timestamp conversions:

Reading from Hive, writing to Iceberg,
```sql
cast(updated_at as timestamp(6)) as updated_at,
--solving Timestamp precision (3) not supported for Iceberg. Use "timestamp(6) with time zone" instead.
```

Reading from Iceberg, writing to Hive,
```sql
cast(updated_at as timestamp) as updated_at,
--solving, NOT_SUPPORTED: Incorrect timestamp precision for timestamp(6); the configured precision is MILLISECONDS
```

This is linked to this issue: https://github.com/trinodb/trino/issues/6658

**Comment by nicor88** [comment]
@mycaule to fix what you describe try to use [this macro](https://github.com/dbt-athena/dbt-athena/blob/e6678691b37390407e7b369b6f3c2277d5b4a720/dbt/include/athena/macros/utils/timestamps.sql#L10C10-L10C24), it's baked in the adapter and should do the right casting automatically
