### ISSUE TITLE
Materialized Tables - Error: (SlowDown) when calling the DeleteObjects operation

### ISSUE THREAD

**Issue by lukealexmiller** [dbt-athena/dbt-athena#480]
I'm experiencing the following error using the adapter when creating many materialized tables:
```
An error occurred (SlowDown) when calling the DeleteObjects operation (reached max retries: 4): Please reduce your request rate.
```

I think the issues arises on [this line](https://github.com/dbt-athena/dbt-athena/blob/cb7050db8105cd23151ce2f583ee849914d9483b/dbt/include/athena/macros/materializations/models/table/create_table_as.sql#L57), as we do not observe any erroring queries in the Athena logs, indicating that the error occurs earlier in the CTAS statement.

The problem occurs for our setup because we have many materialized tables and do not specify unique locations for each table individually, so we hit the S3 limit which yields a 503 response and we quickly run out of retries. 
I'm a little surprised that we encounter this limit at all, as it is (iirc) ~5k/s and each of the 20-30 tables have <30 parquet files in the prefix. 
The prefixes are also unique in the last part of the prefix as we specify: `s3_data_dir: "s3://my-bucket/temp/tables" s3_data_naming: "schema_table_unique"` in the `profile.yml`.

My proposal is to do something like:

1. Add a new configuration parameter to [AthenaCredentials](https://github.com/dbt-athena/dbt-athena/blob/cb7050db8105cd23151ce2f583ee849914d9483b/dbt/adapters/athena/connections.py#L48C7-L48C24), e.g. `num_s3_retries: int = 4` (to maintain current behaviour).
2. Pass the parameter to `get_boto3_config` e.g. [on line 417](https://github.com/dbt-athena/dbt-athena/blob/cb7050db8105cd23151ce2f583ee849914d9483b/dbt/adapters/athena/impl.py#L417C16-L417C16) and other references.
3. Modify `get_boto3_config` to use this parameter as:
```
def get_boto3_config(num_s3_retries: int) -> Config:
    return Config(
        user_agent_extra="dbt-athena-community/" + importlib.metadata.version("dbt-athena-community"),
        retries={
            'max_attempts': num_s3_retries,
            'mode': 'standard'
        }
    )
```

Does this seem logical? I can open a PR if this would make sense. 

I'd also appreciate any feedback or alternative suggestions!

**Comment by nicor88** [comment]
The idea is more or less fine. I'm just not sure about using num_s3_retries or num_retries.

using **num_retries** is nice, because we use an existing config, at the same time **num_s3_retries** is also good because we can control exactly the retries for that specific setup.

@svdimchenko @Jrmyy WDYT?

**Comment by svdimchenko** [comment]
I think we can have both `num_retries` and `num_s3_retries` with default value for `num_s3_retries` set to `num_retries` if `num_s3_retries` is not set

**Comment by nicor88** [comment]
Great, thanks @svdimchenko .

@lukealexmiller we are more than happy to have new contributors, feel free to propose those changes :)
