### ISSUE TITLE
Incompatibility of Bitwise OR Dictionary Merge for Python < 3.9

### ISSUE THREAD

**Issue by mrkre** [dbt-athena/dbt-athena#483]
Line 165 in `dbt/adapters/athena/impl.py` employs the bitwise OR (|) operator for dictionary merging:

```python
config = LfTagsConfig(**(lf_tags_config | dict(inherited_tags=lf_inherited_tags)))
```

This syntax is supported in Python 3.9 and above, but leads to a TypeError in Python versions less than 3.9: `TypeError: unsupported operand type(s) for |: 'dict' and 'dict'`.

Perhaps a version agnostic dictionary merge approach can be taken?

```python
config = LfTagsConfig(**{**lf_tags_config, **{"inherited_tags": lf_inherited_tags}})
```

**Comment by nicor88** [comment]
@mrkre good catch, as we have to support python 3.8, for now, we might need to do what you suggested.

Any reason why you are still on Python 3.8?

**Comment by mrkre** [comment]
Was running dagster + dbt + dbt-athena, and dagster is on 3.8. However, that can be upgraded so it's a non-issue for me. Just caught me by surprise as my pipelines broke in production.

**Comment by nicor88** [comment]
Thanks for the context @mrkre , feel free to open a PR with your proposed changes.

**Comment by nicor88** [comment]
this issue should be covered by https://github.com/dbt-athena/dbt-athena/pull/487 because @svdimchenko refactored the implementation.
Correct me if I'm wrong.
