### ISSUE TITLE
Version 1.6.2 forces user to enter seed_s3_upload_args when it is optional

### ISSUE THREAD

**Issue by JamesZeki** [dbt-athena/dbt-athena#486]
When going from 1.6.0 to 1.6.2 and running dbt init on an existing repository it is forcing you to enter the seed_s3_upload_args (Specify any extra arguments to use in the S3 Upload, e.g. ACL, SSEKMSKeyId):

However, you cannot leave this blank, anything I put int e.g. "ACL" or following the docs to use a disctionary: {"ACL": "bucket-owner-full-control"} also leads to errors when running dbt models or views. Is this an issue with AWS or should it be optional?

![image](https://github.com/dbt-athena/dbt-athena/assets/132580661/51e4955a-0094-450f-9f27-2dbdc74347d5)

**Comment by nicor88** [comment]
@JamesZeki good catch, the issue seems to be related to this https://github.com/dbt-athena/dbt-athena/blob/main/dbt/include/athena/profile_template.yml#L20-L21
I will remove it from the prompts, because it's an optional field and could be added later to the profile.

**Comment by nicor88** [comment]
@JamesZeki the seed_s3_upload_args is now removed from the prompts, changes will be effective once we release a new version.

**Comment by JamesZeki** [comment]
Thanks, much appreciated!
