### ISSUE TITLE
[Communication] Install Slack on the repository to enable release subscription

### ISSUE THREAD

**Issue by remilepriol** [dbt-athena/dbt-athena#523]
Hello all, 
Thank you for the great work on this repo !
To keep up to date with your changes I would like to subscribe via Slack-Github integration with the following command in Slack

    /github subscribe dbt-athena/dbt-athena

But this only works if Slack is installed on this repo. Could you consider installing it ?

**Comment by nicor88** [comment]
@remilepriol do you own if this is possible for github accounts that are not in your own organisation? I'm wondering if you are using a similar approach for other OSS repositories.

**Comment by remilepriol** [comment]
Yes I am subscribed to prefect and dbt-core repos !

**Comment by nicor88** [comment]
@remilepriol could you try again. I was able to install slack on some relevant repos of dbt-athena org.

**Comment by remilepriol** [comment]
Okay it worked. Thank you !
