### ISSUE TITLE
Fine-Grain Permissions make re-creating tables difficult. 

### ISSUE THREAD

**Issue by octiva** [dbt-athena/dbt-athena#546]
Hello, 

I am using `dbt-athena` professionally and think it is a really nice way to orchestrate data operations. 

We use [fine grain permissions](https://docs.aws.amazon.com/lake-formation/latest/dg/access-control-fine-grained.html), with a [multi-account strategy](https://docs.aws.amazon.com/controltower/latest/userguide/aws-multi-account-landing-zone.html). 

I am running into issues when re-creating iceberg tables, where we attempt to drop the `table__ha` before creating it, and as the table has never existed, Lake formation permissions dont allow the `glue:deleteTable` on the entity which doesnt exist. 

Error hit:
```
An error occurred (AccessDeniedException) when calling the DeleteTable operation: User: arn:aws:sts::123456789012/role is not authorized to perform: glue:DeleteTable on resource: arn:aws:glue:region:12356789012/table__ha because no resource-based policy allows the glue:DeleteTable action
```

So, I look into the `native_drop` to see if we can fail the drop via athena and it might be okay. However, `native_drop` does not have any recommended usage, I have tried setting it as both `true` and `"True"` with neither working to change the drop functionality. Does anyone use this regularly and can give me some guidance?  id be happy to update the docs after.

So I think back to the original issue. Why are we trying to delete this table if it doesnt exist and then safely catching an error? Perhaps, we should do a `get_tables` and then work out if the table exists, and clean up if it does before we replace it? 

Any help would be greatly appreciated. Merry Christmas 🎅

**Comment by nicor88** [comment]
Could you provide some more details?
* version of the adapter that you use 
* do you experience this error in the first run (where the target table doesn't exists) or in the incremental runs?

**Comment by octiva** [comment]
Of course @nicor88. And thanks for your input.

`1.7.0`

i do not experience this on the first run, as the table is just created in target location before any tmp swapping logic.

**Comment by nicor88** [comment]
you are right. With iceberg we first "create" an __ha table, then rename the old one to the new one.

One of the issue that I had in the past is that when switching from hive to iceberg, the renaming doesn't work.
Are you by any chance switching a current model (hive) to iceberg?

**Comment by octiva** [comment]
@nicor88 

- Yes, these tables have only been iceberg. Not hive. 
- Yes, the lake-formation permissions are right.  

On that line you linked, the tmp_relation will never be none, as it is actually just a dbt relation that we created above and will always be truthy. 

I propose two ideas to resolve:
1. We dont delete tables before we have created them
2. We search the list of tables for the one: __ha, and only delete if we can see it in the list. (using a `get_table` would be futile as the fine-grain permissions only allow access to entities that exist. 
3. We fail quietly on 403:AccessDenied when we delete, knowing that if the user doesnt have access for future operations, they will get stopped there (no harm no foul)

Im happy to implement any of these over the break, so let me know what you think would be the best resolution

**Comment by nicor88** [comment]
Regarding this, you are right, **tmp_relation** is created via `api.Relation.create` so it's a Python object, and will always be true.

Therefore this
```
{%- if tmp_relation is not none -%}
   {%- do adapter.delete_from_glue_catalog(tmp_relation) -%}
{%- endif -%}
```
Doesn't fully work.
After further debugging in my setup I see this:
`Athena adapter: Table "awsdatacatalog"."dbt_nicola"."iceberg_example_1__ha" does not exists - Ignoring` 

that in my case it's catched, because of [this](https://github.com/dbt-athena/dbt-athena/blob/cbe4c42e3459bbba94d0ada2957e6826cf19c24f/dbt/adapters/athena/impl.py#L326C13-L329C20), but in your case I suspect that due to the fine grain permissions, it's not catched, as it raise a permissions error.

If we talk about solutions, I'm wondering why option 3 will even work for you. - just out of curiosity maybe articulate more why it's an option, because IMHO it's not - I'm for sure not seen something.

So my proposal is the following:

```
{%- if adapter.get_relation(database=tmp_relation.database, schema=tmp_relation.schema, identifier=tmp_relation.identifier)  is not none -%}
   {%- do adapter.delete_from_glue_catalog(tmp_relation) -%}
{%- endif -%}
```
`adapter.get_relation` (see impl [here](https://github.com/dbt-labs/dbt-core/blob/c2bc2f009bbeeb46b3c69d082ab4d485597898af/core/dbt/adapters/base/impl.py#L857)) uses list_relations, that avoid to use `get_table` (as you mentioned), that doesn't work in your scenario.  

Will that work for you?

**Comment by octiva** [comment]
@nicor88 Yes sorry, three was a bad morning thought.. 

I think that solution should work nicely! Do you want me to open a PR? I do not currently have the full dev environment setup but can do so if needed. 

# Notes

- Current setup without LF should be considered a AWS managed policy `AmazonAthenaFullAccess`. This should cover all fine-grained access without LF [more info on managed policy](https://docs.aws.amazon.com/athena/latest/ug/managed-policies.html) [more info on fine-grained glue access](https://docs.aws.amazon.com/athena/latest/ug/fine-grained-access-to-glue-resources.html). As these will fail as expected (Entity not found)

Lake Formation (LF) has 2 main methods: [found here](https://docs.aws.amazon.com/lake-formation/latest/dg/access-control-fine-grained.html)
1. Open, which aligns with existing AWS Glue functionality, which utilises IAM roles. We dont use this, so I cant say I know much, but I imagine it does not suffer the same issues give it is stated that it is backwards compatible. 

2. Fine-grained, AWS recommended method of securing the data lake. 
_granting limited Lake Formation permissions to individual principals on Data Catalog resources, Amazon S3 locations, and the underlying data in those locations_ 
- This is done by Lake Formation using coarse-grained IAM permissions to allow users to create things, and then creating subsequent policies that allow for actions (delete, get, update etc). 

While this is sometimes a little overkill, it reduces the blast radius and risk of malicious actors being able to do to much. 

In terms of cross-account, I recently upgraded `astronomer-cosmos` to allow for role assumption from an airflow connection, meaning we only use temporary credentials in the `profile.yml` so we have not seen any issues in that regard (except for our own incorrect setup at times haha). 

Happy to discuss further in Slack. I will join the dbt channel.

**Comment by nicor88** [comment]
Please submit a PR :) 

Regarding the "Notes" section, many thanks, I will skim it through after the holidays.
