### ISSUE TITLE
(Potential) bug with incremental iceberg tables

### ISSUE THREAD

**Issue by hendrikdreesmann-sc** [dbt-athena/dbt-athena#547]
Hey everyone,

we are getting the following error from time to time: 
 
`GENERIC_INTERNAL_ERROR: io.trino.hdfs.s3.TrinoS3FileSystem$UnrecoverableS3OperationException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; ...)`

The key that is missing is always some metadata file from iceberg, in this case it was an avro file. Not sure if this is dbt-athenas fault or if something else is going on 🤔 Could it be that glue doesn't get updated correctly? Maybe someone already had a similar issue and can help

**Comment by sanromeo** [comment]
Hi, @hendrikdreesmann-sc 

I've seen this error when someone manually deleted files from S3. In Glue Catalog, the path of the table to S3 hasn't changed, and therefore, when you run the query, it tries to take files from a non-existent path, which is why this error appears. 

I usually had this error with test tables, so deleting the table from Glue Catalog and restarting the model helped to solve the problem.

**Comment by nicor88** [comment]
@hendrikdreesmann-sc Do you have by any chance tables sharing the same location? (in dbt-athena we force unique location for iceberg tables), and do you by any chance run any vacuum operation on such tables?

**Comment by hendrikdreesmann-sc** [comment]
Hi @sanromeo and @nicor88,
I don't think this can be the case for the error as this happens in our scheduled dbt runs and we don't delete tables outside of it 🤔 
And the tables should all have their own location 🤔 And we also don't run vacuum yet. Actually we just had the issue again and I investigated a bit. So glue did point to an existing metadata.json, but the manifest file didn't exist. Also there was only one metadata/manifest-list/manifest-file, but I would expect multiple as this table should be updated regularly. Very confusing and I have no idea how I could reproduce this.

**Comment by svdimchenko** [comment]
@hendrikdreesmann-sc do you have any lifecycle policies enabled in your bucker ? is versioning enabled ? 
Anyway if there are no steps to reproduce the bug, we can not fix it 😞

**Comment by hendrikdreesmann-sc** [comment]
Hey @svdimchenko, yea actually I now learned that we do have lifecycle policies enabled on the athena output bucket, which was used because we didn't set the data_dir in the config 😓  So our fault, sorry for taking up your time guys 🙏

**Comment by nicor88** [comment]
@hendrikdreesmann-sc don't worry, it's always a good learning to share.
