### ISSUE TITLE
[Feature] set external_location for iceberg table

### ISSUE THREAD

**Issue by rokity** [dbt-athena/dbt-athena#559]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

With incremental model of iceberg table it's impossible to set `external_location` and also we can't set `s3_data_naming` to values like `table` or `schema_table`. 
For Data Governance , for naming convention in some companies and use cases we need to have a strict naming convention where table path with uuid it's impossible to have.

I'll try to remote the limitation to `external_location` on [create_table.sql ](https://github.com/dbt-athena/dbt-athena/blob/f1af36238c7e5b97c380beaba824fdfa2dee98e1/dbt/include/athena/macros/materializations/models/table/create_table_as.sql#L45)

Just replacing it with `if materialization=table and ('unique' not in s3_data_naming or external_location is not none):
 throw error`
 
 Thanks @nicor88 for support.

### Describe alternatives you've considered

Possibility to use `table` or `schema_table` for `s3_data_naming` .

### Who will this benefit?

For every incremental model with Iceberg when you must to follow a naming convention and a Data Governance organization.

### Are you interested in contributing this feature?

Yes , I'll make PR.

**Comment by nicor88** [comment]
@Jrmyy do you want to chime in too?
