### ISSUE TITLE
dbt seed raise error mismatched input 's' when there is 's in csv file

### ISSUE THREAD

**Issue by grhaonan** [dbt-athena/dbt-athena#60]
Hi team,

I initially raised this issue to dbt-core and it seems fine with dbt-snowflake.

Would you please take a look? the dbt seed will fail if there is a ' character in the seed file

details:

https://github.com/dbt-labs/dbt-core/issues/6306

Thanks

**Comment by cstruct** [comment]
@nicor88 can this be closed since this should already be fixed in #7?

**Comment by nicor88** [comment]
I confirm this issue is fixed. 

I tested using this CSV:
```
country_code,country_name
US,I'm a string
```

@grhaonan plese upgrade to `dbt-athena-community >=1.0.4` if you want to see this issue solved.

**Comment by grhaonan** [comment]
> I confirm this issue is fixed. Thanks @cstruct for pointing out.
> 
> I tested using this CSV:
> 
> ```
> country_code,country_name
> US,I'm a string
> ```
> 
> and all works fine.
> 
> @grhaonan please upgrade to `dbt-athena-community >=1.0.4` if you want to see this issue solved.

Big thanks guys, I will upgrade and try out

Cheers!
