### ISSUE TITLE
[Bug] Adapter error when FIPS mode is enabled

### ISSUE THREAD

**Issue by chrischin478** [dbt-athena/dbt-athena#602]
### Is this a new bug in dbt-athena?

- [X] I believe this is a new bug in dbt-athena
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The Athena adapter is failing for the following error when FIPS is enabled, for example on RHEL>=8.6:

`ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS`

dbt-core had a recent bug dbt-labs/dbt-core#6900 addressing this that was resolved. I think the fix for this would be changing this:

https://github.com/dbt-athena/dbt-athena/blob/40855b36249c9b890bab3c6d77afe88555ad6a85/dbt/adapters/athena/connections.py#L73-L75

To inheret the dbt-core md5 method:
```python
from dbt.utils import md5

@property
def unique_field(self) -> str:
    return f"athena-{md5(self.s3_staging_dir)}"
```

### Expected Behavior

`dbt-athena` runs without FIPS error

### Environment

```markdown
- OS: RHEL8.6 with FIPS mode enabled
- Python: 3.10.12
- dbt: 1.7.10
- dbt-athena-community: 1.7.2
```

**Comment by nicor88** [comment]
@chrischin478 could you try to propose a fix based on your finding?

**Comment by chrischin478** [comment]
@nicor88 I've included the proposal in the description. Let me know what you think.

**Comment by nicor88** [comment]
I've see it, I think is fine to try out what you suggested. 
Looking at dbt-core code seems that the use `md5(self.project_name)`, but what you suggested:

```python
from dbt.utils import md5

@property
def unique_field(self) -> str:
    return f"athena-{md5(self.s3_staging_dir)}"
```
it's totally fine for me.

**Comment by chrischin478** [comment]
Great! I'll get a PR started.
