### ISSUE TITLE
[Feature] Athena dbt-external-tables impl as independent package

### ISSUE THREAD

**Issue by brabster** [dbt-athena/dbt-athena#633]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

We've been waiting for literally years to get an Athena implementation of dbt-external-tables merged. This working repo demonstrates an independent implementation for athena, using dbt-external-tables as an interface and generic impl

https://github.com/brabster/dbt-athena-external-tables

### Describe alternatives you've considered

Merge into dbt-external-tables. Not happened for a long time, if it did happen and any changes needed to be made, it could be problematic getting a response. This solution decouples the Athena implementation without any copy-paste maintenance.

2nd PR to dbt-external-tables, raised May 2023 https://github.com/dbt-labs/dbt-external-tables/pull/203. (All due credit to original PR https://github.com/dbt-labs/dbt-external-tables/pull/133 raised Feb 2022)

### Who will this benefit?

All Athena users wishing to use external tables. dbt-athena-community maintainers who will need to maintain this functionality and would not choose to be tightly coupled to the dbt-external-tables maintainers

### Are you interested in contributing this feature?

I have contributed a working solution. I am not interested in being a maintainer.

**Comment by nicor88** [comment]
Happy to be a maintainer of dbt-external-tables for athena for the time being. @jessedobbelaere seems fine with it too. @Jrmyy @svdimchenko wdyt?

**Comment by brabster** [comment]
I can't transfer, no access. Would one of you like to just create a new repo and init with the contents of this instead? I can put a banned on this deprecating and pointing over to the official one?

![image](https://github.com/dbt-athena/dbt-athena/assets/38702/5c19994b-3ba0-4bfe-b49c-910b4256b477)

**Comment by Jrmyy** [comment]
Hello,

I don't mind supporting also this repository. We did it for athena-utils, it makes sense :)

**Comment by nicor88** [comment]
Thanks @Jrmyy , we can follow up with @brabster to transfer ownership. 3 out of 5 maintainers are in favor.

**Comment by nicor88** [comment]
@brabster marking this as closed because we moved the owership of the repo https://github.com/brabster/dbt-athena-external-tables to https://github.com/dbt-athena/dbt-athena-external-tables
