### ISSUE TITLE
Different table creation strategies for Iceberg

### ISSUE THREAD

**Issue by Jrmyy** [dbt-athena/dbt-athena#64]
Athena engine v3 supports [CTAS](https://docs.aws.amazon.com/athena/latest/ug/create-table-as.html) for Iceberg.

Since engine v2 does not support that, what about adding a `table_strategy` in the table materialization with the following alternatives : `tmp_table` and `ctas`.
- `ctas` is by default for all non iceberg tables and the only possibility.
- `tmp_table` must be set for engine v2 for Iceberg tables.
- `ctas` or `tmp_table` can be chosen for engine v3 for Iceberg tables.

What do you think ?

**Comment by nicor88** [comment]
Nice idea, I like it, so by default our `ctas `

**Comment by Jrmyy** [comment]
https://github.com/dbt-athena/dbt-athena/pull/74#issuecomment-1337015815

Meaning everything will be created using CTAS.
