### ISSUE TITLE
Zero Downtime options for table materialization

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#73]
See this PR: https://github.com/Tomme/dbt-athena/pull/95

Also using iceberg should be quit easy:

```
ALTER TABLE target RENAME TO target_bkp;
ALTER TABLE target_tmp RENAME TO target;

DROP target_bkp; -- only if all is fine
```
It's not 100% downtime, but almost.

Regarding not iceberg table we can do something like this:
* if the table do not exist we use a normal cta in the right location
* if the table exist we:
  * crate the table via cta in a location that is unique 
  * call an glue api update table to use the new location and make a new table version
  * drop the table create in step 1
So pretty much we leverage a table update to add a total new data schema and a new location. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.update_table

**Comment by Jrmyy** [comment]
Right now it is not possible to use the rename command since the rename actually works but an error is raised because results can't be found according to athena API.

A case has been opened by my company on AWS. They are investigation.

**Comment by hiltercoty** [comment]
This can be done by using views but Athena views are not supported by either Spark or Redshift.

**Comment by nicor88** [comment]
As found by @Jrmyy this issue is not longer blocked as the athena team fixed the `ALTER TABLE target RENAME TO ` statement.
