### ISSUE TITLE
Implement `athena__get_tables_by_pattern` macro

### ISSUE THREAD

**Issue by owenprough-sift** [dbt-athena/dbt-athena#75]
https://getdbt.slack.com/archives/C013MLFR7BQ/p1670012162896509

Summary of the above Slack discussion: `codegen` calls `dbt-utils` macro which doesn't work on Athena (see [this issue](https://github.com/dbt-labs/dbt-utils/issues/546)). We could improve the out-of-the box compatibility of this adapter with `codegen` and `dbt-utils` by implementing `athena__get_tables_by_pattern()`.

It might be as easy as copying the implementation from [this PR](https://github.com/dbt-labs/dbt-utils/pull/547/files#diff-e24765dc7a0d3090b0d125041f4a0660847e0d5b435ab346b6226b0ea6dd6e0c) into this adapter.

**Comment by rumbin** [comment]
This is how we locally solved it in our codebase:

```sql
{% macro athena__get_tables_by_pattern_sql(schema_pattern, table_pattern, exclude='', database=target.database) %}

    {% set sql %}
        select distinct
            table_schema as "table_schema",
            table_name as "table_name",
            {{ dbt_utils.get_table_types_sql() }}
        from {{ database }}.information_schema.tables
        where lower(table_schema) like lower('{{ schema_pattern }}')
            and lower(table_name) like lower('{{ table_pattern }}')
            and lower(table_name) not like lower('{{ exclude }}')
        order by
            1, 2
    {% endset %}

    {{ return(sql) }}

{% endmacro %}
```

**Comment by nicor88** [comment]
@owenprough-sift shall we add this macro overwrite in the adapter? I think that can be helpful? anyhow users can still overwrite an overwrite.

**Comment by owenprough-sift** [comment]
That's what makes the most sense to me, yeah. Previously I might have suggested that it belongs in [athena-utils](https://github.com/lalalilo/athena-utils), but I prefer the idea of the adapter itself providing appropriate shims (like the [cross-db macros](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros)). Having these macros defined in the adapter minimizes the extra steps necessary for folks to successfully use this adapter with other packages.

**Comment by owenprough-sift** [comment]
I've moved this issue over to `athena-utils`: https://github.com/lalalilo/athena-utils/issues/5
