### ISSUE TITLE
Implement linting via github actions

### ISSUE THREAD

**Issue by jankatins** [dbt-athena/dbt-athena#8]
I read the [call for help in slack](https://getdbt.slack.com/archives/C013MLFR7BQ/p1666768199324459?thread_ts=1666190334.365239&cid=C013MLFR7BQ) and wanted to ask what kind of linting you want?

My suggestion (based on what I usually implemented in python repos and actually nowadays like):

- black, isort for code formatting
- flake8 + mypy for finding code problems
- pre-commit for running all the linter on commits or on demand (for faster cycle times as you can run the same stuff as in CI), including some linters for whitespace/EOF/... thingies, see e.g. the [wolt cockiecutter example](https://github.com/woltapp/wolt-python-package-cookiecutter/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.pre-commit-config.yaml))
- Github actions to run all pre-commit defined linters on all files

I usually add a small makefile to run the linter/formatter locally on demand (instead of using pre-commit as git pre-commit hook) and setup the local dev virtualenv, either via pip from requirements.txt or via poetry/pyproject.toml, which seems to be the new standard in python packaging (my preference would be the latter... requirements.txt can still be autogenerated).

Not sure what to use for tests, usually it's pytest, but I have no idea how dbt adapters are usually tested. -> leave it out for now?

Would that meet your needs and is this what you had in mind?

**Comment by nicor88** [comment]
Thanks for the issue. What you suggested sounds good to me, except mypy I have black and isort in all my private repos, and I use flake8 for code checks.
When working on a local development, pre-commit is a must, then we can add another Github action to run exactly the same checks of the pre-commit. Generally I have a `make check` locally called in the pre-commit, and the same command is called in the CI.

Regarding tests we need to differentiate at least 2 types:
* unit testing: I was thinking pytest and moto to mock api calls, or simple response mocking with monkeypatch
* integration tests: we can run simple dbt models against a real AWS account, or ideally we can use [localstack](https://docs.localstack.cloud/aws/athena/).

**Comment by jankatins** [comment]
poetry or pip? Is poetry ok?

I would start with just linting and leave running unit testing for later as it is not yet defined.

(another thing for later: adding a release pipeline however that should look like)

**Comment by nicor88** [comment]
Yeah fine let's split a bit up and covering linting first.
I'm fine with Poetry, @thenaturalist any objections?

**Comment by Jrmyy** [comment]
I am also fine with Poetry.

If I sum we want :
- Poetry for dependency management
- Flake8 for code check
- Black and isort for linting
- Pre-commit to ensure smooth developer experience

Am I missing something @nicor88 @jankatins ?

I have some time right, I can start working on that as soon as we release 1.0.4 and 1.3.0 versions 👍🏻

**Comment by nicor88** [comment]
@Jrmyy seems all good. I checked other official providers and seems that poetry is not used. Let's stick with pip for consistency across other adapters. Wdyt?

**Comment by Jrmyy** [comment]
LGTM to keep pip to be consistent with the other adapters 👍🏻
