### ISSUE TITLE
PRs name should follow a convention and be enforced 

### ISSUE THREAD

**Issue by mattiamatrix** [dbt-athena/dbt-athena#80]
PR names should follow conventions and be enforced by the ci.

The community should agree on a convention and implement the necessary steps to enforce it.

Personally, I like [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) format.

See [aws-cdk](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request) for reference.

What do you think?

**Comment by nicor88** [comment]
@mattiamatrix shall we put the convention guidelines in the Readme and in the pr template in case we go for this convention?

**Comment by nicor88** [comment]
@jessedobbelaere nice example. We could install the app, add a section to the Readme too won't hurt, and we might need a semantic.yml file in the .github folder

**Comment by mattiamatrix** [comment]
We can add `CONTRIBUTING.md` and add something like [this](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)
