### ISSUE TITLE
dbt init returns "No adapters available"

### ISSUE THREAD

**Issue by mphuie** [dbt-athena/dbt-athena#82]
Hi there, I've done a `pip install dbt-athena-community` and I'm unable to init a new project.  I'm getting this output.

    23:38:46  Running with dbt=1.3.1
    No adapters available. Go to https://docs.getdbt.com/docs/available-adapters`

I've tried on another machine and running the pip install pointed at the repo with no luck.  I've verified that installing other adapters successfully get detected by `dbt`.

**Comment by nicor88** [comment]
This issue should be fixed when we release this change: https://github.com/dbt-athena/dbt-athena/pull/59

**Comment by Jrmyy** [comment]
This is now fixed when using the version `1.3.3` of this adapter ! 🎉
