### ISSUE TITLE
Separate table type from table format

### ISSUE THREAD

**Issue by Jrmyy** [dbt-athena/dbt-athena#84]
👋🏻 Hello

Right now, when we use our adapter we can set format to `parquet`, `iceberg`, `json` ... The issue with that is that with the new implementation of `create_table_as` we are mixing `table_type` and `table_format` and we enforce that iceberg tables are in parquet format. This is ok right now because parquet is the best format to put with Iceberg but it would be great to have 2 parameters when defining models :
- `table_type` : `format` or `iceberg`
- `format` : `parquet`, `avro`, `json`, `text`

What do you think ?

**Comment by nicor88** [comment]
I like the proposed naming, just some more suggestions:

* table_type: can be `external`, `iceberg` (that is managed)
then the regarding format, this means when we have table_type=iceberg we cannot support the all format, but parquet/orc I guess
I was also thinking about that when I saw your PR about iceberg.

**Comment by Jrmyy** [comment]
For the table_type, it is just to stick to the table_type in [CTAS](https://docs.aws.amazon.com/athena/latest/ug/create-table-as.html) definition. So you mean then we will need to map external to hive right ?

**Comment by nicor88** [comment]
@Jrmyy ah I've seen it now the docs, then table_type can be HIVE or ICEBERG, default to HIVE.

> How does that affect things is table_type is not set?

@pixie79 we will have a default behavior, HIVE, that pretty much leave the actual setup unchanged.
