### ISSUE TITLE
Issue on consecutive run on incremental model 

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#89]
The first run works, when I run for the second time the model get stuck. No error raised.

```
{{ config(
    materialized='incremental',
    format='parquet',
    incremental_strategy='insert_overwrite',
    partitioned_by=['report_date']
) }}

SELECT
    999999 AS cost,
    cast(t.ts AS date) as report_date
FROM unnest(sequence(cast('2022-10-01' AS date), cast('2022-12-04' AS date), INTERVAL '1' Day)) AS t(ts)
```

**Comment by Jrmyy** [comment]
👋🏻 Hello

I tried the exact same model and it takes like forever (2 minutes and a half) (the delete overlapping partitions take way too much time) and then I have this :

> GENERIC_INTERNAL_ERROR: java.lang.NullPointerException: storageFormat is null.

When doing the insert :

```sql
-- /* {"app": "dbt", "dbt_version": "1.3.1", "profile_name": "jt_data_models", "target_name": "dev_v3", "node_id": "model.jt_data_models.test_io"} */

    
    insert into test_dbt_athena.test_io ("cost", "report_date")
    (
       select "cost", "report_date"
       from test_dbt_athena.test_io__dbt_tmp
    )
```

**Comment by Jrmyy** [comment]
**Update :** This model works when built using the v2 engine. Only the v3 engine is concerned.

**Comment by Jrmyy** [comment]
**Update :** A case has been opened by my company on that subject, they have to come back to me since they have an increase in this issue.

**Comment by Jrmyy** [comment]
Update : AWS Support told me it was resolved. I checked and it is ok. This was a bug on Athena side, it is working now. Closing as not an issue with the adapter.
