### ISSUE TITLE
iceberg merge: configure if nulls should be updated

### ISSUE THREAD

**Issue by aartaria** [dbt-athena/dbt-athena#91]
Would come handy to be able to customize further the behaviour of the merge approach in order to be able to decide whether nulls should be updated during the merge step

NOTE: This behaviour is custom and diverges from the standard dbt macro so it might not really fit here.

As a footprint I will anyway link a reference implementation of such a feature:

https://github.com/ringier-data/dbt-athena/tree/feature/iceberg_merge_update_nulls

**Comment by nicor88** [comment]
@aartaria for your implementation looks like that in case of null values we leave the field untouched, leaving the old values untouched, did I got it right?

**Comment by aartaria** [comment]
@nicor88 made some improvements over the previous version:

* [feat: support merge_update_columns merge_exclude_columns](https://github.com/ringier-data/dbt-athena/commit/cc9968de6ca4720c005f460904f379f85527ee88)
* [feat: introduce merge_update_columns_rules](https://github.com/ringier-data/dbt-athena/commit/345e95d928b560b170d589b37c265b2c3ca595b1)

**Comment by nicor88** [comment]
@aartaria it will be good to understand your use cases in order to access the implementation.
Regarding the 2 improvements, fell free to open one pr that cover both to avoid conflicts.
